# ======================================================================
# Workflow Name: Terraform Deploy (Reusable)
# Purpose: Reusable workflow that deploys Terraform infra (Function App,
#          EventHub, IoT Hub routing, etc.) using OIDC login and remote backend.
# ======================================================================
 
name: Terraform Deploy (Reusable)
 
on:
  workflow_call:
    inputs:
      tf_root:
        description: "Terraform root directory"
        type: string
        required: false
        default: "infra"
      tf_apply:
        description: "Terraform Apply true/false"
        type: string
        required: false
        default: "true"
      app_insights:
        description: "Enable Application Insights"
        type: string
        required: false
        default: "true"
      language_version:
        description: "Language version (unused here, passed through for parity)"
        type: string
        required: false
        default: "3.10"
      external_repo:
        description: "External repository to checkout"
        type: string
        required: false
      deploy_env:
        description: "Resolved deployment environment (from setup job)"
        type: string
        required: true
      version_tag:
        description: "Version tag from semantic-versioning"
        type: string
        required: false
      # -------- NEW: allow caller to pass IoT Hub name (or set env/repo var IOTHUB_NAME) --------
      iothub_name:
        description: "Name of the existing IoT Hub (fallback to vars.IOTHUB_NAME)"
        type: string
        required: false
 
permissions:
  id-token: write
  contents: read
 
env:
  TF_WORKING_DIR: ${{ inputs.tf_root || 'infra' }}
  TF_VERSION: "1.9.5"
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
 
    steps:
      - name: Checkout (repo or external)
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.external_repo || github.repository }}
 
      - name: Download build ZIP (from same run)
        uses: actions/download-artifact@v4
        with:
          name: function-zip
 
      - name: Ensure dist path
        shell: bash
        run: |
          mkdir -p dist
          [[ -f function.zip ]] && mv function.zip dist/function.zip || true
          ls -lah dist
 
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: false
 
      - name: Export ARM_* for Terraform OIDC
        shell: bash
        run: |
          echo "ARM_USE_OIDC=true" >> "$GITHUB_ENV"
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> "$GITHUB_ENV"
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> "$GITHUB_ENV"
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> "$GITHUB_ENV"
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
 
      - name: Prepare backend container (existing SA)
        id: backend
        shell: bash
        run: |
          set -euo pipefail
          RG="${{ vars.STATE_RG }}"
          SA="${{ vars.STATE_STORAGE }}"
          CN="${{ vars.STATE_CONTAINER }}"
          KEY="${{ vars.STATE_KEY }}"
 
          echo "Using existing storage account: $SA (RG: $RG)"
          az storage account show --name "$SA" --resource-group "$RG" --only-show-errors 1>/dev/null
 
          echo "Fetching access key..."
          ACCOUNT_KEY="$(az storage account keys list \
            --resource-group "$RG" \
            --account-name "$SA" \
            --query '[0].value' -o tsv)"
 
          if [[ -z "$ACCOUNT_KEY" ]]; then
            echo "Failed to obtain storage account key for $SA" >&2
            exit 1
          fi
 
          echo "::add-mask::$ACCOUNT_KEY"
          echo "ACCOUNT_KEY=$ACCOUNT_KEY" >> "$GITHUB_OUTPUT"
 
          echo "Ensuring container '$CN' exists..."
          az storage container create \
            --name "$CN" \
            --account-name "$SA" \
            --account-key "$ACCOUNT_KEY" \
            --only-show-errors 1>/dev/null
 
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: bash
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=${{ vars.STATE_RG }}" \
            -backend-config="storage_account_name=${{ vars.STATE_STORAGE }}" \
            -backend-config="container_name=${{ vars.STATE_CONTAINER }}" \
            -backend-config="key=${{ vars.STATE_KEY }}" \
            -backend-config="access_key=${{ steps.backend.outputs.ACCOUNT_KEY }}"
 
      # -------- NEW: resolve + validate IoT Hub name (caller input or env/repo var) --------
      - name: Resolve IoT Hub inputs
        shell: bash
        run: |
          IOTHUB_NAME="${{ inputs.iothub_name || vars.IOTHUB_NAME }}"
          if [ -z "$IOTHUB_NAME" ]; then
            echo "::error::IoT Hub name is required. Set workflow input 'iothub_name' or environment/repo variable 'IOTHUB_NAME'."
            exit 1
          fi
          echo "IOTHUB_NAME=$IOTHUB_NAME" >> "$GITHUB_ENV"
          # If IoT Hub lives in a different RG than your deployment RG, optionally set IOTHUB_RG and export TF_VAR_iothub_resource_group too.
          # echo "IOTHUB_RG=${{ vars.IOTHUB_RESOURCE_GROUP || vars.RESOURCE_GROUP }}" >> "$GITHUB_ENV"
 
      - name: Export TF Vars
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: bash
        run: |
          echo "TF_VAR_app_acronym=${{ vars.APP_ACRONYM }}" >> "$GITHUB_ENV"
          echo "TF_VAR_app_insights_enabled=${{ inputs.app_insights || 'true' }}" >> "$GITHUB_ENV"
          echo "TF_VAR_function_name=${{ vars.FUNCTION_NAME }}" >> "$GITHUB_ENV"
          echo "TF_VAR_artifact_zip=${{ github.workspace }}/dist/function.zip" >> "$GITHUB_ENV"
          echo "TF_VAR_seq_number=${{ vars.SEQ_NUMBER }}" >> "$GITHUB_ENV"
          echo "TF_VAR_location=${{ vars.AZ_LOCATION }}" >> "$GITHUB_ENV"
          echo "TF_VAR_location_acronym=${{ vars.LOC_ACRONYM }}" >> "$GITHUB_ENV"
          echo "TF_VAR_environment=${{ inputs.deploy_env }}" >> "$GITHUB_ENV"
          echo "TF_VAR_resource_group=${{ vars.RESOURCE_GROUP }}" >> "$GITHUB_ENV"
          echo "TF_VAR_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> "$GITHUB_ENV"
          echo "TF_VAR_storage_account_name=${{ vars.STORAGE_ACCOUNT_NAME }}" >> "$GITHUB_ENV"
          echo "TF_VAR_storage_container_name=function-releases" >> "$GITHUB_ENV"
          echo "TF_VAR_eventhubs_namespace=${{ vars.EVENTHUBS_NAMESPACE }}" >> "$GITHUB_ENV"
          echo "TF_VAR_log_analytics_name=${{ vars.LOG_ANALYTICS_NAME }}" >> "$GITHUB_ENV"
          echo "TF_VAR_function_service_plan_name=${{ vars.FUNCTION_SERVICE_PLAN_NAME }}" >> "$GITHUB_ENV"
          echo "TF_VAR_version_tag=${{ inputs.version_tag || format('0.0.{0}', github.run_number) }}" >> "$GITHUB_ENV"
          echo "TF_VAR_build_number=${{ github.run_number }}" >> "$GITHUB_ENV"
          # -------- NEW: hand IoT Hub name to Terraform --------
          echo "TF_VAR_iothub_name=${IOTHUB_NAME}" >> "$GITHUB_ENV"
          # If using a distinct RG for IoT Hub, also export:
          # echo "TF_VAR_iothub_resource_group=${IOTHUB_RG}" >> "$GITHUB_ENV"
 
      - name: Confirm ZIP is readable
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: bash
        run: |
          ls -lah "${{ github.workspace }}/dist"
          test -r "${{ github.workspace }}/dist/function.zip"
 
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: bash
        run: terraform plan -input=false -no-color -out=tfplan
 
      - name: Terraform Apply
        if: ${{ inputs.tf_apply == 'true' }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: bash
        run: terraform apply -input=false -auto-approve tfplan